### ISSUE TITLE
SONAME bump

### ISSUE THREAD

**Issue by fvcr** [libyal/libvhdi#15]
Hi Joachim Metz,

I've been preparing to package the new release of libvhdi for Debian,
I found a small obstacle ahead, there was a change in ABI, some interfaces were added and others were removed, as we can see in:
https://salsa.debian.org/fvcr/libvhdi/-/commit/31c90371c7d0d97b8f89e88824bcd73e0543d45e
I believe that the removal of some interfaces should cause a bump of SONAME.

What do you think about bumping SONAME to reflect the backwards compatibility breakage in the new releases?
As other software that depends on the removed interfaces/functions will have to be checked and rebuilt against it.

Regards,
Francisco.

**Comment by joachimmetz** [comment]
> As other software that depends on the removed interfaces/functions will have to be checked and rebuilt against it.

This library has alpha status and what that means is documented in https://github.com/libyal/libyal/wiki. 
```
alpha; code is a bit more mature than experimental but still work in progress, things will likely change;
```

Why didn't Debian reach out before adding it to the package repository to check if this was a good decision?

**Comment by joachimmetz** [comment]
> As other software that depends on the removed interfaces/functions will have to be checked and rebuilt against it.

which other software ?

**Comment by fvcr** [comment]
> 
> Why didn't Debian maintainers reach out before adding it to the package repository to check if this was a good decision?

that's why I'm contacting you,

nothing has changed in the official repository:
https://tracker.debian.org/libvhdi
https://salsa.debian.org/pkg-security-team/libvhdi

these are my changes:
https://salsa.debian.org/fvcr/libvhdi

my intention is to have more fresh software in the repositories but so far there has been no change to libvhdi.

Thanks!

**Comment by fvcr** [comment]
> > As other software that depends on the removed interfaces/functions will have to be checked and rebuilt against it.
> 
> which other software ?

these are:

Reverse-Build-Depends
* dfvfs                         (for python3-libvhdi)
* plaso                         (for python3-libvhdi)
* pytsk                         (for libvhdi-dev)
* sleuthkit                     (for libvhdi-dev)

**Comment by joachimmetz** [comment]
> that's why I'm contacting you,

ah good to hear,

> nothing has changed in the official repository:
> my intention is to have more fresh software in the repositories but so far there has been no change to libvhdi.

oh they are very behind, thanks for looking into this

> these are:
> Reverse-Build-Depends

So the SONAME should not affect dfvfs and plaso. Both are Python and require pyvhdi which should be the same version as libvhdi.

pytsk, will depend, if built hermetically (not using libtsk) then vhdi support is disabled
otherwise libvhdi is really a dependency of libtsk

sleuthkit (libtsk) only uses a couple of libvhdi API functions

Checking with `git whatchanged -p include/libvhdi.h.in` I don't see any mayor API (and therefore ABI) changes in the last ~4 years; a couple of functions added and a couple of non-functional write functions were removed.

Are there particular functions you are concerned about?

**Comment by samueloph** [comment]
Hello @joachimmetz, I work on the same team that currently maintains the libvhdi package on Debian and I hope I can help.

Just to make it clear, libvhdi is currently packaged on the Debian repositories, it's only the latest version which is not there. I can say that we do not try to package software that is not stable enough and I'm sorry nobody contacted you when the package got introduced. This lib was initially packaged because it was a dependency of plaso, back in 2015, and nowadays is also a dependency of sleuthkit (another somewhat important package).

> Checking with git whatchanged -p include/libvhdi.h.in I don't see any mayor API (and therefore ABI) changes in the last ~4 years; a couple of functions added and a couple of non-functional write functions were removed.

I really appreciate how you are being proactive in checking for breakages here.
I think the main concern we had was with SONAME standing still while the API was changing in non-backwards compatible ways. 

When such thing happens we can look at our official repos and make sure nothing broke there, but there might be users of the library (this includes users outside Debian) which might have compiled something against the old symbols. This users risk having breakages when running their binaries with a newer version of the lib. (I trust you are familiar with this issue, just explaining it here for the record).

The goal of this issue was to bring the risk to your attention, as sometimes it might slip off. I do understand now that you were aware of it and that you don't want to bump the version because libvhdi is in alpha.[0]

Please don't take this as a pressure to move libvhdi to stable or bump the version; I believe you might find it useful to know that the library is packaged by the following distros:
https://repology.org/project/libvhdi/versions

[0] As the goal of the issue was achieved, feel free to resolve it.

Thanks for quick and detailed replies :)

**Comment by joachimmetz** [comment]
> I think the main concern we had was with SONAME standing still while the API was changing in non-backwards compatible ways.

Acknowledged. Note that if functional methods are replaced they will be annotated with [LIBVHDI_DEPRECATED](https://github.com/libyal/libvhdi/blob/master/include/libvhdi/features.h.in#L41) for some time first. If, and this is a big if, projects that use libvhdi as a dependency keep it up to date and realize it is still alpha status they should be fine.

Also note that not every operating system uses SONAME, so other means are needed to inform these from backwards compatibility changes.

> library is packaged by the following distros: https://repology.org/project/libvhdi/versions

Hmm, I only think a few of these have actually reached out (several are Debian derivatives so I'm considering them as a single group). Worrying to see that so many have out of date versions. I'm wondering if a more continuous integration testing approach could benefit keeping packaged software up to date?

Closing as the issue has been addressed.

**Comment by samueloph** [comment]
> Acknowledged. Note that if functional methods are replaced they will be annotated with LIBVHDI_DEPRECATED for some time first. If, and this is a big if, projects that use libvhdi as a dependency keep it up to date and realize it is still alpha status they should be fine.

Awesome,

> Also note that not every operating system uses SONAME, so other means are needed to inform these from backwards compatibility changes.

Hmm, I'm not familiar with alternatives for SONAME, at least none other than adding a big notice in the changelog. I'd be interested in reading more about that if you have studying resources to recommend.

> Hmm, I only think a few of these have actually reached out (several are Debian derivatives so I'm considering them as a single group). 

Yes, generally speaking (there's always exceptions), you can assume that the packages of the following distros originally came from Debian:
Kali Linux
Ubuntu
Linux Mint
PureOS
Raspbian
Parrot

Though it's up for the derivative to keep the package up to date after they sync from Debian.

> Worrying to see that so many have out of date versions. I'm wondering if a more continuous integration testing approach could benefit keeping packaged software up to date?

Providing CI is always welcomed but I don't think it would change the situation, my guess is that it's outdated either because it's a stable release and they only backport critical fixes or they don't have personnel/enough available time to package the newer releases. It's also not every distro* which has a CI system so this reduces the impact for this matter.

> Closing as the issue has been addressed.

Thanks,

\* In Debian we do have https://ci.debian.net/ which continuously runs and it's integrated with our packaging trackers.

**Comment by joachimmetz** [comment]
> In Debian we do have https://ci.debian.net/ which continuously runs and it's integrated with our packaging trackers.

This is for Debian package maintainers only correct? It is not something like Travis CI or AppVeyor that can be invoked on release build by project maintainers?

**Comment by samueloph** [comment]
> This is for Debian package maintainers only correct? It is not something like Travis CI or AppVeyor that can be invoked on release build by project maintainers?

Unfortunately no, this CI process is for the Debian packages per se, so the target has to be a package that is already on the repository, builds are done when build dependencies are changed and on new uploads, we can also trigger new tests by authenticating with our Debian Developer credentials. Basically the way we get the automated CI is by uploading the package to either Debian experimental or unstable.

We also trigger autopkgtest(the tool which runs the tests for debci) when we do a git push on our packaging repos (we use gitlab CI for that), but again these tests target Debian packages so they only work if you have the packaging metadata.

Example of a pipeline run of autopkgtest
https://salsa.debian.org/debian/rsync/-/pipelines/168851

**Comment by joachimmetz** [comment]
ack, thx
